FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app

CMD ["rq", "worker", "--url", "redis://redis:6379/0", "--job-monitoring-interval", "5", "--logging_level", "INFO", "imagegen"]
